bat/users/urls.py
from allauth.account.views import confirm_email
from django.urls import include, path
from rest_auth.registration.views import VerifyEmailView
from rest_auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetView,
)
from rest_framework_jwt import views as jwt_views
from rest_framework_nested.routers import DefaultRouter
from allauth.account.views import confirm_email
from rest_auth.views import (
    LogoutView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetView,
)
from rest_auth.registration.views import VerifyEmailView

from rest_framework_jwt import views as jwt_views

from bat.users.views import InvitationViewSet, RolesandPermissionsViewSet, UserViewSet, \
    UserLoginActivityViewSet, LoginView

app_name = "users"

router = DefaultRouter()

router.register("user", UserViewSet)
router.register("invitations", InvitationViewSet)
router.register("login-activities", UserLoginActivityViewSet)
router.register(
    "role-permissions", RolesandPermissionsViewSet, basename="role-permissions"
)


urlpatterns = [path("", include(router.urls))]

urlpatterns += [
    path(
        "password/reset/",
        PasswordResetView.as_view(),
        name="rest_password_reset",
    ),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/confirm/",
        PasswordResetConfirmView.as_view(),
        name="rest_password_reset_confirm",
    ),
    path("login/", LoginView.as_view(), name="rest_login"),
    # URLs that require a user to be logged in with a valid session / token.
    path("logout/", LogoutView.as_view(), name="rest_logout"),
    path(
        "password/change/",
        PasswordChangeView.as_view(),
        name="rest_password_change",
    ),
    path("token-refresh/", jwt_views.refresh_jwt_token),
    path(
        "registration/account-confirm-email/<key>",
        confirm_email,
        name="account_confirm_email",
    ),  # redirect to verify-email and POST key
    path(
        "verify-email/", VerifyEmailView.as_view(), name="verify_email"
    ),  # POST value of key
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

admin.autodiscover()
urlpatterns = [
    path("admin/", admin.site.urls),
    # defender admin
    path("admin/defender/", include("defender.urls")),
    path("accounts/", include("allauth.urls")),
    # Django Invitation
    path("invitations/", include("invitations.urls", namespace="invitations")),
    path("ht", include("health_check.urls", namespace="ht")),
    # API base url
    path("", include("config.api_router")),
    path("summernote/", include("django_summernote.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

bat/company/forms.py
"""Froms related to Company app."""
import logging
from decimal import Decimal

from bat.company.models import (Bank, Company, CompanyPaymentTerms, HsCode,
                                Location, Member, PackingBox, Tax)
from bat.setting.models import Category
from bat.users.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Column, Layout, Row, Submit
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from invitations.utils import get_invitation_model

logger = logging.getLogger(__name__)
Invitation = get_invitation_model()


class CompanyForm(forms.ModelForm):
    """Company Form."""

    class Meta:
        """Defining Model and fields."""

        model = Company
        fields = (
            "name",
            "address1",
            "address2",
            "zip",
            "city",
            "region",
            "country",
            "abbreviation",
            "email",
            "logo",
            "phone_number",
            "organization_number",
            "currency",
            "unit_system",
            "weight_unit",
            "language",
            "time_zone",
        )


class CompanyUpdateForm(forms.ModelForm):
    """Company Update Form."""

    class Meta:
        """Defining Model and fields."""

        model = Company
        fields = (
            "name",
            "abbreviation",
            "address1",
            "address2",
            "zip",
            "city",
            "region",
            "country",
            "email",
            "logo",
            "phone_number",
            "organization_number",
            "currency",
            "unit_system",
            "weight_unit",
            "language",
            "time_zone",
        )

    def __init__(self, *args, **kwargs):
        """Init basic fields."""
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.attrs = {"novalidate": ""}
        self.helper.layout = Layout(
            HTML("<h5 class='mb-4'>Company Detail</h5>"),
            Row(
                Column("name", css_class="col-md-8"),
                Column("abbreviation", css_class="col-md-4"),
                css_class="form-row",
            ),
            Row(
                Column("logo", css_class="col-md-3"),
                Column("email", css_class="col-md-3"),
                Column("phone_number", css_class="col-md-3"),
                Column("organization_number", css_class="col-md-3"),
                css_class="form-row",
            ),
            HTML("<h5 class='mb-4'>Company Address</h5>"),
            Row(
                Column("address1", css_class="col-md-6"),
                Column("address2", css_class="col-md-6"),
                css_class="form-row",
            ),
            Row(
                Column("zip", css_class="col-md-3"),
                Column("city", css_class="col-md-3"),
                Column("region", css_class="col-md-3"),
                Column("country", css_class="col-md-3"),
                css_class="form-row",
            ),
            HTML("<h5 class='mb-4'>Standards and formats</h5>"),
            Row(
                Column("time_zone", css_class="col-md-3"),
                Column("language", css_class="col-md-3"),
                Column("unit_system", css_class="col-md-3"),
                Column("weight_unit", css_class="col-md-3"),
                css_class="form-row",
            ),
            HTML("<h5 class='mb-4'>Currency</h5>"),
            Row(
                Column("currency", css_class="col-md-6"), css_class="form-row"
            ),
            Submit("submit", _("Update Profile")),
        )


class MemberForm(forms.ModelForm):
    """Member Form."""

    job_title = forms.CharField(
        label=_("Job Title"), max_length=100, required=True
    )
    roles = forms.CharField(widget=forms.HiddenInput)
    permissions = forms.CharField(widget=forms.HiddenInput)
    company_id = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        """Defining Model and fields."""

        model = User
        fields = (
            "job_title",
            "first_name",
            "last_name",
            "email",
            "roles",
            "permissions",
            "company_id",
        )

    def __init__(self, *args, **kwargs):
        """
        Call the __inti__ method before assigning.

        override form field properties and same thing we will use when we
        need to create two form like create and update
        """
        super().__init__(*args, **kwargs)
        self.fields["email"].label = _("Email address")
        self.fields["email"].required = True
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True

    def clean(self):
        """
        Perform validation on Email and company.

        Fetch email field and perform validation like unique email in database
        or some other custom validation. you can raise error for perticular
        field from here that will be display as error on the formself.
        """
        cleaned_data = super().clean()
        company_id = cleaned_data.get("company_id")
        email = cleaned_data.get("email")
        if company_id and email:
            if Member.objects.filter(
                company_id=int(company_id), user__email=email
            ).exists():
                msg = _("User already is your staff member.")
                raise ValidationError(msg)
            else:
                invitations = Invitation.objects.filter(
                    email=email, company_detail__company_id=int(company_id)
                )
                if invitations.exists():
                    msg = _("Invitation already sent for this email.")
                    raise ValidationError(msg)


class MemberUpdateForm(forms.ModelForm):
    """Member Update Form."""

    roles = forms.CharField(widget=forms.HiddenInput)
    permissions = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        """Defining Model and fields."""

        model = Member
        fields = ("job_title", "roles", "permissions")


class AccountSetupForm(forms.ModelForm):
    """Member Form."""

    class Meta:
        """Defining Model and fields."""

        model = Company
        fields = (
            "name",
            "address1",
            "address2",
            "zip",
            "city",
            "region",
            "country",
            "abbreviation",
            "email",
            "phone_number",
        )

    def __init__(self, *args, **kwargs):
        """Init basic fields."""
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.attrs = {"novalidate": ""}
        self.helper.layout = Layout(
            Row(
                Column("name", css_class="col-md-8"),
                Column("abbreviation", css_class="col-md-4"),
                css_class="form-row",
            ),
            "address1",
            "address2",
            Row(
                Column("zip", css_class="col-md-4"),
                Column("city", css_class="col-md-4"),
                Column("region", css_class="col-md-4"),
                css_class="form-row",
            ),
            "country",
            Row(
                Column("email", css_class="col-md-6"),
                Column("phone_number", css_class="col-md-6"),
                css_class="form-row",
            ),
            Submit("submit", _("COMPLETE REGISTERATION")),
        )


class VendorInviteForm(forms.ModelForm):
    """Vendor Invitation Form."""

    vendor_type = forms.ChoiceField(label=_("Vendor Type"), required=True)
    vendor_name = forms.CharField(
        label=_("Vendor Name"), max_length=100, required=True
    )
    job_title = forms.CharField(
        label=_("Job Title"), max_length=100, required=True
    )

    class Meta:
        """Defining Model and fields."""

        model = User
        fields = (
            "vendor_type",
            "vendor_name",
            "job_title",
            "first_name",
            "last_name",
            "email",
        )

    def __init__(self, *args, **kwargs):
        """
        Call the __inti__ method before assigning.

        override form field properties and same thing we will use when we
        need to create two form like create and update
        """
        super().__init__(*args, **kwargs)
        categories = Category.objects.filter(parent__name__exact=_("Vendors"))
        self.fields["email"].label = _("Email address")
        self.fields["email"].required = True
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        self.fields["vendor_type"].choices = (
            (category.pk, category.name) for category in categories
        )

    def clean(self):
        """
        Perform validation on Email and company.

        Fetch email field and perform validation like unique email in database
        or some other custom validation. you can raise error for perticular
        field from here that will be display as error on the formself.
        """
        cleaned_data = super().clean()
        vendor_type = cleaned_data.get("vendor_type")
        vendor_name = cleaned_data.get("vendor_name")
        email = cleaned_data.get("email")
        if vendor_type and vendor_name and email:
            invitations = Invitation.objects.filter(
                email=email, company_detail__company_name__iexact=vendor_name
            )
            if invitations.exists():
                msg = _("Invitation already sent for this vendor and email.")
                raise ValidationError(msg)


class CompanyPaymentTermsForm(forms.ModelForm):
    """Payment Terms Form."""

    class Meta:
        """Defining Model and fields."""

        model = CompanyPaymentTerms

bat/users/views.py
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from invitations.utils import get_invitation_model
from notifications.signals import notify
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.mixins import RetrieveModelMixin, UpdateModelMixin
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from rest_auth.views import LoginView as BaseLoginView

from bat.company.utils import get_list_of_roles_permissions
from bat.users import serializers

from bat.users.models import UserLoginActivity

User = get_user_model()
Invitation = get_invitation_model()


class LoginView(BaseLoginView):
    def post(self, request, *args, **kwargs):
        self.request = request
        self.serializer = self.get_serializer(data=self.request.data,
                                              context={'request': request})
        self.serializer.is_valid(raise_exception=True)

        self.login()
        self.user.first_login = False
        self.user.save()
        return self.get_response()


class UserViewSet(
    RetrieveModelMixin, UpdateModelMixin, viewsets.GenericViewSet
):
    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer
    permission_classes = (IsAuthenticated,)
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        """
        filter query for current user
        """
        # return self.queryset.filter(username=self.kwargs.get("username"))
        return self.queryset.filter(username=self.request.user.username)


class RolesandPermissionsViewSet(viewsets.ViewSet):
    def list(self, request):
        """
        list available Roles and Permissions for user
        """
        all_roles = get_list_of_roles_permissions()
        return Response(all_roles, status=status.HTTP_200_OK)


class InvitationViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Invitation.objects.all()
    serializer_class = serializers.InvitationSerializer

    def filter_queryset(self, queryset):
        """
        filter invitations for current user.
        return pending invitations
        """
        queryset = super().filter_queryset(queryset)
        queryset = queryset.filter(
            accepted=False, email=self.request.user.email
        )

        invite_key = self.request.GET.get('inviteKey', None)
        if invite_key:
            queryset = queryset.filter(key=invite_key)
        return queryset

    @action(detail=True, methods=["post"])
    def accept(self, request, pk=None):
        """
        accept invitation
        and perform signals to complete tasks
        """
        instance = self.get_object()
        instance.accepted = True
        instance.save()
        post_save.send(
            User, instance=self.request.user, created=False, using=None
        )
        return Response(
            {"detail": _("Accepted successfully")}, status=status.HTTP_200_OK
        )

    @action(detail=True, methods=["post"])
    def reject(self, request, pk=None):
        """
        reject invitation
        and notify sender
        """
        instance = self.get_object()
        notify.send(
            self.request.user,
            recipient=instance.inviter,
            verb=_("Rejected your invitation"),
            target_id=instance.company_detail["company_id"],
        )
        instance.delete()
        return Response(
            {"detail": _("Rejected successfully")}, status=status.HTTP_200_OK
        )


class UserLoginActivityViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = UserLoginActivity.objects.all()
    serializer_class = serializers.UserLoginActivitySerializer

    def get_queryset(self, *args, **kwargs):
        """
        filter query for current user
        """
        return self.queryset.filter(user=self.request.user)

bat/users/templates/user/roles/edit.html
{% extends "base.html" %}
{% load static crispy_forms_tags permission_tags %}
{% block title %}
User Roles
{% endblock title %}
{% block amazonsidebar %}{% endblock %}
{% block content %}
<h1>User Roles</h1>

<div class="separator mb-5"></div>
<div class="row">
  <div class="col-12">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="mb-4">Assign/Change User Roles</h5>

        {% if success %}
        <div class="alert alert-success rounded" role="alert">
          {{ success }}
        </div>
        {% endif %}


        <form method="POST" enctype="multipart/form-data" class="needs-validation" id="perm-assign-form" novalidate>

          <label for="" class="col-form-label requiredField">Roles & Permissions</label>
          {% crispy form form.helper %}

          {% for e in form.roles.errors %}
          <p class="invalid-feedback d-block"><strong>{{e}}</strong></p>
          {% endfor %}


          <div class="row mt-2">
            <div class="col">
              <div class="accordion" id="rolesAssignment">
                {% for role, meta in available_roles.items %}
                <div class="card shadow-none border mb-2">
                  <div class="card-header pb-0" id="heading{{role}}">
                    <div class="custom-control custom-checkbox my-3">
                      <input type="checkbox" class="custom-control-input role-selector" id="customCheck-{{role}}"
                        {% if role_user|has_role:role %}checked{% endif %} data-role="{{role}}" />
                      <label class="custom-control-label h6" for="customCheck-{{role}}">
                        {{meta.display_name}}
                      </label>

                      <button class="btn btn-link p-0 float-right" type="button" data-toggle="collapse"
                        data-target="#collapse{{role}}" aria-expanded="true" aria-controls="collapse{{role}}}}">
                        <h5 class="mb-0"><i class="iconsmind-Arrow-Down font-weight-bold"></i></h5>
                      </button>
                    </div>
                  </div>

                  <div id="collapse{{role}}" class="collapse show" aria-labelledby="heading{{role}}"
                    data-parent="#rolesAssignment">
                    <div class="card-body pt-1">
                      <div class="row pl-3">
                        {% for perm, perm_name in meta.permissions.items %}
                        <div class="col-lg-3">
                          <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input perm-selector"
                              {% if role_user|can:perm %}checked{% endif %} id="perm-{{perm}}" data-role="{{role}}"
                              data-perm="{{perm}}" />
                            <label class="custom-control-label" for="perm-{{perm}}">{{perm_name}}</label>
                          </div>
                        </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>


          <button type="submit" class="btn btn-primary mb-0">Submit</button>
          <a href="{% url 'accounts:list_roles' %}" class="btn btn-danger mb-0">Cancel</a>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}

<script type="text/javascript">
  $(".role-selector").on('change', function () {
    var role = $(this).data('role');
    var selected = $(this)[0].checked;
    $("[data-role='" + role + "']").prop('checked', selected);
  });

  $("#perm-assign-form").on('submit', function (e) {
    var selectedRoles = [];
    var selectedPerms = [];
    $(".role-selector:checked").each(function (idx, el) {
      selectedRoles.push($(this).data('role'));
    });

    $(".perm-selector:checked").each(function (idx, el) {
      if (selectedRoles.indexOf($(this).data('role')) === -1)
        selectedRoles.push($(this).data('role'));
      selectedPerms.push($(this).data('perm'));
    });
    $("#id_roles").val(selectedRoles.join(","));
    $("#id_permissions").val(selectedPerms.join(","));
    return true;
  });
</script>
{% endblock %}

bat/users/templates/user/roles/list.html
{% extends "base.html" %}
{% load static user_utils permission_tags %}
{% block title %}
User Roles
{% endblock title %}
{% block amazonsidebar %}{% endblock %}
{% block content %}
<h1>User Roles</h1>

<div class="separator mb-5"></div>
<div class="row">
  <div class="col-12">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="mb-4">Assign/Change User Roles</h5>

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} rounded" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}

        <table class="data-table responsive nowrap">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Username</th>
              <th>Roles</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for user in object_list %}
            <tr>
              <td>
                <p class="list-item-heading">{{ user.get_full_name }}</p>
              </td>
              <td>
                <p class="list-item-heading">{{user.email}}</p>
              </td>
              <td>
                <p class="list-item-heading">{{user.username}}</p>
              </td>
              <td>
                <p>
                  {% for role in user.roles %}
                    {{ role.get_name | formattedRoleName }}{% if forloop.last %}{% else %}, {%endif %}
                  {% endfor %}
                </p>
              </td>
              <td>
                <a href="{% url 'accounts:update_roles' user.id %}" class="btn btn-outline-info icon-button ">
                  <i class="simple-icon-pencil"></i>
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}